### ISSUE TITLE
Iris example does not work

### ISSUE THREAD

**Issue by f-guitart** [Appverse/DriftAI#6]
I have just downloaded the repo, installed following the instructions in Mac and using conda.

All tests passed.

Then I go to examples/iris and run:

`bash project-setup.sh`

I get the following error:

```
(p37_driftai) macbookfrancesc:iris francesc$ bash project-setup.sh 
Traceback (most recent call last):
  File "download_iris.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/Users/francesc/anaconda3/envs/p37_driftai/bin/dai", line 11, in <module>
    load_entry_point('driftai==0.1', 'console_scripts', 'dai')()
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/cli.py", line 76, in add
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/dataset.py", line 146, in read_file
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/dataset.py", line 41, in __init__
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/datasource.py", line 188, in get_infolist
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/datasource.py", line 208, in _load_csv
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/datasource.py", line 227, in get_data
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/pandas-0.24.2-py3.7-macosx-10.7-x86_64.egg/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/pandas-0.24.2-py3.7-macosx-10.7-x86_64.egg/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/pandas-0.24.2-py3.7-macosx-10.7-x86_64.egg/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/pandas-0.24.2-py3.7-macosx-10.7-x86_64.egg/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/pandas-0.24.2-py3.7-macosx-10.7-x86_64.egg/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/Users/francesc/work/udl/repos/DriftAI/examples/iris/data/iris.csv' does not exist: b'/Users/francesc/work/udl/repos/DriftAI/examples/iris/data/iris.csv'
Traceback (most recent call last):
  File "/Users/francesc/anaconda3/envs/p37_driftai/bin/dai", line 11, in <module>
    load_entry_point('driftai==0.1', 'console_scripts', 'dai')()
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/cli.py", line 126, in generate
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/cli.py", line 88, in generate_subdataset
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/dataset.py", line 274, in __init__
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/data/dataset.py", line 336, in _generate_indices
AttributeError: 'NoneType' object has no attribute 'infolist'
Traceback (most recent call last):
  File "/Users/francesc/anaconda3/envs/p37_driftai/bin/dai", line 11, in <module>
    load_entry_point('driftai==0.1', 'console_scripts', 'dai')()
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/cli.py", line 126, in generate
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/cli.py", line 98, in generate_approach
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/db/persistent.py", line 15, in save
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/db/db.py", line 72, in save
  File "/Users/francesc/anaconda3/envs/p37_driftai/lib/python3.7/site-packages/driftai-0.1-py3.7.egg/driftai/approach.py", line 209, in get_info
AttributeError: 'NoneType' object has no attribute 'id'
Approach with id logistic_regression does not exist.

```

**Comment by sulfur1c** [comment]
Hi @f-guitart 

It is working fine with windows environment, as I do not have any MAC to test issue I can not help in that.

Kind regards.
